### ISSUE TITLE
ViewModel support

### ISSUE THREAD

**Issue by inshiro** [rewe-digital/katana#5]
First of all I'd like to thank you guys. This is my first time using dependency injection and I learned a lot from playing around with Katana. Having somewhat similar syntax to Koin, Kodein, and Dagger, made it that much easier for me to cross-reference and learn DI in general.

Seeing as there's no support for `ViewModel`(?) I created my own. What do you guys think?
```kotlin
/**
 * A ViewModelFactory that works alongside dependency injection.
 *
 * @param viewModel The already injected ViewModel.
 * @return A ViewModelProvider.Factory to be used with ViewModelProviders.of
 */
class KatanaViewModelFactory(private val viewModel: ViewModel) : ViewModelProvider.Factory {
    override fun <T : ViewModel?> create(modelClass: Class<T>): T = viewModel as? T ?: modelClass.newInstance()
}


/**
 * Declares a [ViewModel] dependency binding as a singleton.
 * Only one instance (per component) will be created.
 *
 * The ViewModelFactory is also created here because we need the unique class name of your [ViewModel].
 * @param body Body of binding declaration
 *
 * @see Module.factory
 * @see Module.singleton
 */
inline fun <reified T : ViewModel> Module.viewModel(crossinline body: ProviderDsl.() -> T) {
    val name : String = T::class.java.simpleName
    singleton<ViewModel>(name, body = body)
    singleton(name = "${name}Factory") { KatanaViewModelFactory(get(name)) }
}


/**
 * Inject the ViewModel declared from [Module.viewModel].
 *
 * The scope is tied to the host [Activity]. This is called from a [Fragment].
 * @return [ViewModel]
 */
inline fun <reified VM : ViewModel, T> T.viewModel(): Lazy<VM> where T : KatanaTrait, T : Fragment =
        lazy { ViewModelProviders.of(requireActivity(), injectNow("${VM::class.java.simpleName}Factory")).get(VM::class.java) }


/**
 * Inject the ViewModel declared from [Module.viewModel].
 * This is called from an [Activity].
 * @return [ViewModel]
 */
inline fun <reified VM : ViewModel, T> T.viewModel(): Lazy<VM> where T : KatanaTrait, T : AppCompatActivity =
        lazy { ViewModelProviders.of(this, injectNow("${VM::class.java.simpleName}Factory")).get(VM::class.java) }


/**
 * Inject the ViewModel declared from [Module.viewModel] with an assignment operator.
 *
 * The scope is tied to the host [Activity]. This is called from a [Fragment].
 * @return [ViewModel]
 */
// This has conflicts with the above. Use this if you're using [KatanaFragmentDelegate]
// and you're inside the onInject callback.
/* inline fun <reified VM : ViewModel,T> T.viewModel(): VM where T: KatanaTrait, T: Fragment=
   ViewModelProviders.of(requireActivity(),injectNow("${VM::class.java.simpleName}Factory")).get(VM::class.java)
*/
```
The `module` creation would look something like this
```Kotlin
createModule {
        singleton { ApplicationDatabase.getInstance(Application.instance) }
        singleton { get<ApplicationDatabase>().mainDao() }
        singleton { MainRepository.getInstance(get()) }
        viewModel { MainViewModel(get()) }
    }
```
Inject it in your `Activity`/`Fragment`:
```kotlin
val viewModel: MainViewModel by viewModel()
```

**_Side notes (For modules that depend on activities):_**
In fragments you can `inject()` and declare a `Component` without callbacks by using `lazy`.
You just have to do **everything** in `onActivityCreated` because of the Activity-Fragment relationship.
But I think you already know this.

> `KatanaFragmentDelegate.kt`:
> Since Fragments are instantiated **before** Activities, the component initialization must be delayed until the Activity was created.

```kotlin
class MyFragment : Fragment(), KatanaTrait {
    // All of these are by lazy
    override val component: Component by lazy { getComponent() }
    private val viewModel: MainViewModel by viewModel()
    private val myObj: MyObject by inject()

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        // Don't put code here that relies on activity dependencies
    }
    
    override fun onActivityCreated(savedInstanceState: Bundle?) {
        super.onActivityCreated(savedInstanceState)
        // Put it here
        viewModel.doStuff()
        myObj.doStuff()
    }
}
```

**Comment by svenjacobs** [comment]
Hi @inshiro, thanks for your contribution! I will look at this in more detail in the next few days and think about how this can be integrated into Katana, of course crediting your work appropriately.

**Comment by inshiro** [comment]
Sometimes I get a `ClassNotFoundException`. I believe this is due to R8 (I used fullMode). Once I set that to false, no more exceptions...

**Comment by inshiro** [comment]
Sometimes I get a `ClassNotFoundException`. I believe this is due to R8 (I used fullMode). Once I set that to false, no more exceptions...
```gradle
java.lang.NoClassDefFoundError: Failed resolution of: Lna/komi/kodesh/ui/main/Modules$mainModule$1$viewModel$$inlined$singleton$2;
        at na.komi.kodesh.ui.main.Modules$mainModule$1.invoke(MainModule.kt:84)
        at na.komi.kodesh.ui.main.Modules$mainModule$1.invoke(MainModule.kt:16)
        at org.rewedigital.katana.ModuleKt.createModule(Module.kt:12)
        at org.rewedigital.katana.ModuleKt.createModule$default(Module.kt:10)
        at na.komi.kodesh.ui.main.Modules.getMainModule(MainModule.kt:19)
        at na.komi.kodesh.ui.main.MainComponent.getMainComponent(MainComponent.kt:28)
        at na.komi.kodesh.ui.main.MainActivity.<init>(MainActivity.kt:14)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2831)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "na.komi.kodesh.ui.main.Modules$mainModule$1$viewModel$$inlined$singleton$2" on path: DexPathList[[zip file "/data/app/na.komi.kodesh-finky-D0rZuaRn6rdIKMEA==/base.apk", zip file "/data/app/na.komi.kodesh-finky-D0rZuaRn6rdIKMEA==/split_lib_dependencies_apk.apk", zip file "/data/app/na.komi.kodesh-finky-D0rZuaRn6rdIKMEA==/split_lib_resources_apk.apk", zip file "/data/app/na.komi.kodesh-finky-D0rZuaRn6rdIKMEA==/split_lib_slice_0_apk.apk", zip file "/data/app/na.komi.kodesh-finky-D0rZuaRn6rdIKMEA==/split_lib_slice_1_apk.apk", zip file "/data/app/na.komi.kodesh-finky-D0rZuaRn6rdIKMEA==/split_lib_slice_2_apk.apk", zip file "/data/app/na.komi.kodesh-finky-D0rZuaRn6rdIKMEA==/split_lib_slice_3_apk.apk", zip file "/data/app/na.komi.kodesh-finky-D0rZuaRn6rdIKMEA==/split_lib_slice_4_apk.apk", zip file "/data/app/na.komi.kodesh-finky-D0rZuaRn6rdIKMEA==/split_lib_slice_5_apk.apk", zip file "/data/app/na.komi.kodesh-finky-D0rZuaRn6rdIKMEA==/split_lib_slice_6_apk.apk", zip file "/data/app/na.komi.kodesh-finky-D0rZuaRn6rdIKMEA==/split_lib_slice_7_apk.apk", zip file "/data/app/na.komi.kodesh-finky-D0rZuaRn6rdIKMEA==/split_lib_slice_8_apk.apk", zip file "/data/app/na.komi.kodesh-finky-D0rZuaRn6rdIKMEA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/na.komi.kodesh-finky-D0rZuaRn6rdIKMEA==/lib/arm64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at na.komi.kodesh.ui.main.Modules$mainModule$1.invoke(MainModule.kt:84) 
        at na.komi.kodesh.ui.main.Modules$mainModule$1.invoke(MainModule.kt:16) 
        at org.rewedigital.katana.ModuleKt.createModule(Module.kt:12) 
        at org.rewedigital.katana.ModuleKt.createModule$default(Module.kt:10) 
        at na.komi.kodesh.ui.main.Modules.getMainModule(MainModule.kt:19) 
        at na.komi.kodesh.ui.main.MainComponent.getMainComponent(MainComponent.kt:28) 
        at na.komi.kodesh.ui.main.MainActivity.<init>(MainActivity.kt:14) 
        at java.lang.Class.newInstance(Native Method) 
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69) 
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41) 
        at android.app.Instrumentation.newActivity(Instrumentation.java:1215) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2831) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/na.komi.kodesh-finky-D0rZuaRn6rdIKMEA==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
2019-03-13 23:35:29.725 7433-7433/na.komi.kodesh E/AndroidRuntime:     at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:727)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:810)
        at android.app.LoadedApk.getResources(LoadedApk.java:1032)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2345)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5749)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        		... 6 more
```

**Comment by svenjacobs** [comment]
I'm not really sure if this is related to Katana and/or your ViewModel changes. I believe R8 has an issue with too many nested lambdas (nested classes in bytecode). There was a similiar discussion on [Slack](https://kotlinlang.slack.com/archives/CDR81TX99/p1550655712003200) and the fix was to move an inner class outside of the Katana module binding. Did you find a R8 rule that fixes this issue?

**Comment by svenjacobs** [comment]
@inshiro I "slightly" changed your code 😉 however your code was a good start and helped me a lot since I haven't worked with `ViewModel` much lately. What do you think of this [solution](https://github.com/rewe-digital/katana/blob/feature/androidx-viewmodel/androidx-viewmodel/src/main/kotlin/org/rewedigital/katana/androidx/viewmodel/ViewModel.kt)?

**Comment by svenjacobs** [comment]
Closing issue as ViewModel support has been released with version 1.4.0 of Katana.
Please let me know if you have any feedback.

**Comment by inshiro** [comment]
Works great! Thanks for the support!
btw I don't know if it's just me but `implementation "org.rewedigital.katana:katana-androidx-viewmodel:1.4.0"` isn't working for me so I just downloaded the artifact and put it in my project.

**Comment by svenjacobs** [comment]
> btw I don't know if it's just me but implementation "org.rewedigital.katana:katana-androidx-viewmodel:1.4.0" isn't working for me so I just downloaded the artifact and put it in my project.

Initially I forgot to adjust `.travis.yml` and deploy the new artifact to Bintray. But I fixed that a few minutes ago. New artifact should be on JCenter soon.

**Comment by svenjacobs** [comment]
**Update**: Bintray still needs to approve upload of new artifact to JCenter. I hope this doesn't take too long...

In the meantime the artifact can be downloaded from [Bintray](https://bintray.com/rewe-digital/katana/katana-androidx-viewmodel/1.4.0).

**Update 2**: The artifact is now on JCenter.
